let listings = [
    {
        id: 1,
        image: "./media/9-Humewood-Dr-Toronto-ON-Primary-Photo-1.jpg",
        location: "52 Cliffwood Road,North York, Toronto, Ontario, Canada",
        price: "$1,500,000",
        availability: "Available",
        description: "Canada International is pleased to present this 5 unit multifamily property in the desirable neighbourhood of Cliffwood Society. This property presents investors with an opportunity to acquire a character building in the advantageous rental market of Toronto.",
        type: "Apartment",
        squareFeet: 1200,
        units: 6,
        bathrooms: 6,
        kitchen: 6,
        balconies: 6,
        hall: 1,
        parking: "Available",
        locker: "Available",
        moreImages: ["./media/9-Humewood-Dr-Toronto-ON-Primary-Photo-1.jpg", 
        "./media/9-Humewood-Dr-Toronto-ON-Primary-Photo-2.jpg"]
    },
    {
        id: 2,
        image: "./media/15-Burrard-Rd-Toronto-ON-Primary-Photo-1.jpg",
        location: "15 Burrard Road, Toronto, ON, Canada",
        price: "$1,487,468",
        availability: "Available",
        description: "Brand New Cash Flowing Legal Triplex With Rents Of $105,600 (4.9% Cap Rate)! 3 Self-Contained Units With Private Entrances Each Consisting Of 2 Beds And 2 Baths (1 En-Suite), Separate Utilities, Onsite Parking And In-Unit Laundry.",
        type: "Apartment",
        squareFeet: 1050,
        units: 3,
        bathrooms: 3,
        kitchen: 1,
        balconies: 3,
        hall: 1,
        parking: "Not Available",
        locker: "Available",
        moreImages: ["./media/15-Burrard-Rd-Toronto-ON-Primary-Photo-1.jpg", "./media/15-Burrard-Rd-Toronto-ON-Primary-Photo-2.jpg", "./media/15-Burrard-Rd-Toronto-ON-Primary-Photo-3.jpg"]
    },

    {
        id: 3,
        image: "./media/869-Broadview-Av-Toronto-ON-Building-Photo-1.jpg",
        location: "869 Broadview Av, Toronto, ON, Canada",
        price: "$2,975,080",
        availability: "Available",
        description: "GIncredible opportunity to purchase a well managed 15+1 unit apartment building in Playter Estates. Steps to the Broadview subway and prime Danforth Avenue.",
        type: "Apartment",
        squareFeet: 5040,
        units: 16,
        number_of_stories: 3,
        kitchen: 16,
        balconies: 16,
        hall: 2,
        parking: "Available",
        locker: "Available",
        moreImages: ["./media/869-Broadview-Av-Toronto-ON-Building-Photo-1.jpg", "./media/869-Broadview-Av-Toronto-ON-Building-Photo-2.jpg"]
    },
    {
        id: 4,
        image: "./media/132QDale.jpg",
        location: "132 Queensdale Ave, East York, ON M4J 1Y4, Canada",
        price: "$2,550,000",
        availability: "Available",
        description: "Serene and tranquil multi-story home in East York offering a peaceful and elegant living experience.",
        type: "House",
        squareFeet: 2300,
        bedrooms: 4,
        bathrooms: 2,
        kitchen: 1,
        balconies: 1,
        hall: 1,
        parking: "Not Available",
        locker: "Available",
        moreImages: ["./media/132QDale.jpg", "./media/132QDale_2.jpg", "./media/132QDale_3.jpg", "./media/132QDale_4.jpg"]
    },
    {
        id: 5,
        image: "./media/2183-Lake-Shore-Blvd-W-Toronto-ON-Primary-Photo-1.jpg",
        location: "12183 Lake Shore Blvd W, Toronto,ON, Canada",
        price: "$2,417,256",
        availability: "Sold",
        description: "Charming apartment in the quiet neighborhood of Scarborough with beautiful interior design.",
        type: "Condominium",
        squareFeet: 3841,
        bedrooms: 5,
        bathrooms: 3,
        kitchen: 1,
        balconies: 1,
        hall: 2,
        parking: "Available",
        locker: "Not Available",
        moreImages: ["./media/2183-Lake-Shore-Blvd-W-Toronto-ON-Primary-Photo-1.jpg"]
    },
    {
        id: 6,
        image: "./media/39IngWdDrv.jpg",
        location: "39 Inglewood Dr, North York, ON M4T 1G9, Canada",
        price: "$1,400,000",
        availability: "Sold",
        description: "Impressive house in North York, nestled in a peaceful neighborhood with excellent amenities.",
        type: "House",
        squareFeet: 2500,
        bedrooms: 4,
        bathrooms: 3,
        kitchen: 1,
        balconies: 2,
        hall: 1,
        parking: "Available",
        locker: "Not Available",
        moreImages: ["./media/39IngWdDrv.jpg", "./media/39IngWdDrv_2.jpg", "./media/39IngWdDrv_3.jpg"]
    }
    
];
